"""initial schema

Revision ID: 51c8defea338
Revises: 
Create Date: 2026-06-27 14:27:26.445146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51c8defea338'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # This is a baseline migration — all 11 tables already exist on Render
    # (created via raw SQL). This revision exists only so that `alembic stamp
    # head` can mark the database as being at this revision.  Future
    # autogenerated migrations will produce real diffs from this point forward.
    pass


def downgrade() -> None:
    # Intentionally empty — the baseline cannot be downgraded.
    pass

