"""add submitted_at and approved_at to results

Revision ID: a04de3cb5f51
Revises: 7964f1e7ce50
Create Date: 2026-07-23 16:35:51.104844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a04de3cb5f51'
down_revision: Union[str, None] = '7964f1e7ce50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('exam_types_name_unique'), 'exam_types', type_='unique')
    op.add_column('results', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    op.add_column('results', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('subjects_code_key'), 'subjects', type_='unique')
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=True)
    op.drop_constraint(op.f('teachers_email_key'), 'teachers', type_='unique')
    op.drop_constraint(op.f('teachers_teacher_id_key'), 'teachers', type_='unique')
    op.drop_index(op.f('ix_teachers_email'), table_name='teachers')
    op.create_index(op.f('ix_teachers_email'), 'teachers', ['email'], unique=True)
    op.drop_index(op.f('ix_teachers_teacher_id'), table_name='teachers')
    op.create_index(op.f('ix_teachers_teacher_id'), 'teachers', ['teacher_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teachers_teacher_id'), table_name='teachers')
    op.create_index(op.f('ix_teachers_teacher_id'), 'teachers', ['teacher_id'], unique=False)
    op.drop_index(op.f('ix_teachers_email'), table_name='teachers')
    op.create_index(op.f('ix_teachers_email'), 'teachers', ['email'], unique=False)
    op.create_unique_constraint(op.f('teachers_teacher_id_key'), 'teachers', ['teacher_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('teachers_email_key'), 'teachers', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=False)
    op.create_unique_constraint(op.f('subjects_code_key'), 'subjects', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_column('results', 'approved_at')
    op.drop_column('results', 'submitted_at')
    op.create_unique_constraint(op.f('exam_types_name_unique'), 'exam_types', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
